CREATE TABLE IF NOT EXISTS vehicles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_code TEXT UNIQUE NOT NULL,
    vin TEXT,
    year INTEGER,
    make TEXT,
    model TEXT,
    engine TEXT,
    purchase_price NUMERIC(10,2),
    auction_source TEXT,
    acquired_at DATE,
    notes TEXT,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS vehicle_photos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_code TEXT NOT NULL,
    file_path TEXT NOT NULL,
    public_url TEXT,
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS inventory_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku TEXT UNIQUE NOT NULL,
    item_type TEXT DEFAULT 'Part',
    source_type TEXT DEFAULT 'Misc',
    vehicle_code TEXT,
    item_name TEXT NOT NULL,
    category TEXT,
    oem_number TEXT,
    condition TEXT,
    shelf_location TEXT,
    status TEXT DEFAULT 'New',
    ask_price NUMERIC(10,2),
    min_price NUMERIC(10,2),
    quantity INTEGER DEFAULT 1,
    vendor_name TEXT,
    notes TEXT,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS item_photos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku TEXT NOT NULL,
    file_path TEXT NOT NULL,
    public_url TEXT,
    photo_type TEXT DEFAULT 'general',
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS listing_packages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku TEXT UNIQUE NOT NULL,
    title TEXT,
    description TEXT,
    price NUMERIC(10,2),
    ready_to_publish BOOLEAN DEFAULT FALSE,
    validation_errors TEXT,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS listing_channels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku TEXT NOT NULL,
    platform TEXT NOT NULL,
    listing_url TEXT,
    platform_listing_id TEXT,
    listing_status TEXT DEFAULT 'draft',
    published_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku TEXT NOT NULL,
    platform TEXT,
    sold_price NUMERIC(10,2),
    fees NUMERIC(10,2) DEFAULT 0,
    commission_rate NUMERIC(5,2),
    commission_amount NUMERIC(10,2),
    client_payout NUMERIC(10,2),
    sold_at TIMESTAMP DEFAULT NOW(),
    notes TEXT
);

ALTER TABLE vehicles ENABLE ROW LEVEL SECURITY;
ALTER TABLE vehicle_photos ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE item_photos ENABLE ROW LEVEL SECURITY;
ALTER TABLE listing_packages ENABLE ROW LEVEL SECURITY;
ALTER TABLE listing_channels ENABLE ROW LEVEL SECURITY;
ALTER TABLE sales ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow all vehicles" ON vehicles;
CREATE POLICY "Allow all vehicles" ON vehicles FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all vehicle photos" ON vehicle_photos;
CREATE POLICY "Allow all vehicle photos" ON vehicle_photos FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all inventory items" ON inventory_items;
CREATE POLICY "Allow all inventory items" ON inventory_items FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all item photos" ON item_photos;
CREATE POLICY "Allow all item photos" ON item_photos FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all listing packages" ON listing_packages;
CREATE POLICY "Allow all listing packages" ON listing_packages FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all listing channels" ON listing_channels;
CREATE POLICY "Allow all listing channels" ON listing_channels FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all sales" ON sales;
CREATE POLICY "Allow all sales" ON sales FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

GRANT SELECT, INSERT, UPDATE, DELETE ON vehicles TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON vehicle_photos TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON inventory_items TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON item_photos TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON listing_packages TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON listing_channels TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON sales TO anon, authenticated;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;
